### ISSUE TITLE
autorisation, new user system

### ISSUE THREAD

**Issue by dennis071nl** [Luc-S/Toon-HASS#11]
Since the latest release , the new user system is implemented. I tried to connect my TOON to a fresh install and i cannot get the connection working.. 
Is there a simple work around??

**Comment by Luc-S** [comment]
I had a quick read up and see that I’ve got some work to do for implementing this :)

There should be a ‘legecy mode’ available in Home Assistant, maybe you can turn this on until we implemented this new user management system?

**Comment by dennis071nl** [comment]
Luc, 

I tried to connect using the type: legacy_api_password in my config,yaml but unfortunately i cannot connect. Any ideas??

**Comment by Luc-S** [comment]
I've updated to HomeAssistant 0.78.0 and have indeed the same issue. Other things seem to be functioning fine with the legacy_api_password like bringing up the JSON from a browser.

I'll have to enable some logging to see what's happening. Will try to continue tomorrow.

**Comment by Luc-S** [comment]
Hey Dennis, I noticed that it's probably related to SSL. Do you use Home Assistant also on SSL? I receive no response whatsoever when I leave SSL enabled in the configuration.yaml (http response 0, not even 401 or whatever). When I disabled SSL for Home Assistant I got some responses again.

My certificate was expired so I had to renew (auto renew didn't work for some reason, have to look into that later :p). When implementing SSL I struggled a lot with certificates so I have to play around again, I'm not really familiar with certificates :(

**Comment by Luc-S** [comment]
Hmm, I have nothing in my logs but that could be a difference in our hardware/installation. 

If that error really corresponds with our issues you would think that maybe the Toon SSL handler became too old for Home Assistant? Don’t even know if that’s possible though but I hope it’s something else... something easier :p

**Comment by Luc-S** [comment]
As my certificates were expired and last time it took me ages to get them working I now lack a good environment to test so I checked if an online REST tool could retrieve a valid Home Assistant JSON which it couldn't. Also a 0 response.

After trying some things out I got the online REST tool working with adding this to the configuration.yaml of Home Assistant (in the http section):

```
http:
  <other http configuration stuff>
  cors_allowed_origins:
    - '*'
```

It would be great if you could check this out on your environment. My Toon still doesn't work but this could be because of the new certificates.

**Comment by dennis071nl** [comment]
Luc,

unfortunately still no connection...

dennis

Op do 20 sep. 2018 om 20:39 schreef Luc_S <notifications@github.com>:

**Comment by Luc-S** [comment]
Because I had to make sure my certificates were fine again I rolled back my Home Assistant and got everything sorted again on HA version 0.69.1

Btw, you only need the root certificate on Toon to make SSL work. I don't know if you followed my how-to on domoticaforum.eu by any chance but I updated the post a little bit.

I tried some HA versions and it breaks between 0.72.1 and 0.73.1. Next version to try 0.73.0 :)

**Comment by Luc-S** [comment]
Version 0.73.0 breaks the connection because of this update:

- Stop supporting deprecated TLS ciphers (@hmmbob - #15217) (http docs) (breaking change)

In 0.73.0 I was able to rollback the changed `__init__.py` file of Home Assistant and got it working again. This is however not a solution as more changes are made to this file in later Home Assistant versions (for version 0.78.2 I got lost in all things changed in order to fix this matter). I'll have to see what my options are here.

**Comment by Luc-S** [comment]
Yeah got it! :) Got it working again on version 0.78.3. You need to add this to the http: section in your HA configuration.yaml

```
http:
  <other http stuff>
  ssl_profile: intermediate
```

**Comment by Luc-S** [comment]
For some reason domoticaforum.eu is not responding anymore so I hope you get a notification for a message through here;

> Even zien, ik heb veel er weer uitgehaald omdat ik gedowngrade had;
> 
> In de homeassistant: heb ik die hele auth_providers er weer uitgehaald. (Met dat legacy_api_password)
> 
> In de http: heb ik geen cors_allowed_origin meer:
> 
> http:
>   api_password: xxx
>   server_port: 8123
>   ssl_certificate: /home/.....
>   ssl_key: /home/.....
>   base_url: xxx.duckdns.org
>   ssl_profile: intermediate
> 
> 
> Er zit een kleine bug in de Toon app die als de connectie mislukt, de SSL button weer uitzet. Moet wel weer aan :)

**Comment by dennis071nl** [comment]
Luc...

Aaagghhhh, driving me nuts...

hoe kun je checken of de certificaten kloppen op de toon? rest staat nu
exact zoals bij jou namelijk...


Op za 22 sep. 2018 om 22:28 schreef Luc_S <notifications@github.com>:

**Comment by Luc-S** [comment]
Haha ja is lastig dat certificaat gebeuren. Is ook niet fatsoenlijk te checken op de Toon :(

Je had het laatst over de ‘fullchain’, daarmee heb ik het nooit mee voor elkaar gekregen.

Als je in de Toon naar /etc/ssl/certs/ gaat en doet ‘ls -l’ dan zou je daar je hoofd certificaat moeten zien staan met een pijltje naar de .crt file locatie in /usr/share/ca-certificates/xxx.crt

Bij mij staat er dan:
DST_Root_CA_X3.pem -> /usr/share/ca-certificates/DST_Root_CA.crt

Had je mijn post gevonden/gevolgd over certificaten op domoticaforum.eu? In het topic over deze app op pagina 2. Daar staat hoe ik het voor elkaar heb gekregen.

**Comment by Luc-S** [comment]
`update-ca-certificates --fresh`

Vergeet ook niet de xxx.crt toe te voegen aan file `/etc/ca-certificates.conf`. Dat refresh command gebruikt die file om die certificaten toe te voegen als trusted.

**Comment by dennis071nl** [comment]
check, nu reboot..

laatste poging voor vandaag hoor...:-)))

Op za 22 sep. 2018 om 23:27 schreef Luc_S <notifications@github.com>:

**Comment by Luc-S** [comment]
Haha ok. Verder heb ik in app configuratie op de Toon:
server: xxx.duckdns.org
port: 443
pass: je HA password

**Comment by dennis071nl** [comment]
mmm, stapje verder... :-) geen foutmeldung maar oook geen schakelaars....:-(

Op za 22 sep. 2018 om 23:39 schreef Luc_S <notifications@github.com>:

**Comment by Luc-S** [comment]
Geen foutmelding klinkt in ieder geval goed. Heb je friendly names ingesteld voor de schakelaars die je hebt toegevoegd in je config? Ik heb vast niet alle mogelijke issues netjes afgevangen.

Check voor de zekerheid nog even de installation guide hier op Github, misschien staat er iets in wat je nog anders hebt staan?

Je hebt ook niet per ongeluk de switches in het scherm van sensoren gezet o.i.d.? Haal anders alle objecten er even uit en probeer 1 sensor.

**Comment by dennis071nl** [comment]
Luc,

Ik heb volgens mij alle stappen gezet die in de tutorial staan, maar ik
krijg HA niet werkend op de Toon, kan verder ook niets vinden in logs,
dus... Zou je me alsblieft nog even willen helpen om t eea werkend te
krijgen????

Dennis

Op za 22 sep. 2018 om 23:56 schreef Luc_S <notifications@github.com>:

**Comment by Luc-S** [comment]
Ja hoor. Ik weet niet in hoeverre je zelf al dingen hebt geprobeerd dus laten we gewoon eens kijken hoe ver we komen. Probeer eens via je pc/laptop browser naar de URL te gaan van de HA api. Krijg je een JSON resultaat als je daarheen gaat?

De URL zou er zo uit moeten zien:
https://ha-url/api/states?api_password=wachtwoord_van_je_HA

Voor mijn systeem zou dat er dan ongeveer zo uit zien:
https://homesystem.duckdns.org/api/states?api_password=w@chtw00rd

Ik krijg dan een lange lijst aan attributen en hun properties in een JSON formaat.

**Comment by Luc-S** [comment]
Haha je hoeft hem inderdaad niet te sturen, ik geloof het wel :)

Bouw die URL dan eens om naar een switch met exact de naam die je in de Toon hebt geconfigureerd;
https://homesystem.duckdns.org/api/states/switch.kaku1?api_password=w@chtw00rd

Dan zou je de properties van die switch moeten krijgen. Krijg je dat en zit er ook een friendly_name bij?

**Comment by dennis071nl** [comment]
Ik heb geen enkele switch of scene of light kunnen instellen in de Toon...
ik heb verbinding (iig geen foutmelding meer) maar ik zie niks... scherm op
de toon is leeg verder...

Dus heb niks in te stellen...

Mn HA bevat wel verschillende switches, lights en scenes, dus zou iig iets
verwachten...



Op do 27 sep. 2018 om 09:31 schreef Luc_S <notifications@github.com>:

**Comment by dennis071nl** [comment]
en mn vnc is echt baggertraag dus ik kan je even geen screenshot laten
zien...:-(

Op do 27 sep. 2018 om 09:34 schreef Dennis Smit <dennis@dennissm.it>:

**Comment by dennis071nl** [comment]
Maar als ik t doe met een willekeurige sensor dan krijg ik wel resultaat
terug..!˜

"

{"attributes": {"friendly_name": "Toon Gas Used Cnt", "icon":
"mdi:fire", "unit_of_measurement": "m3"}, "context": {"id":
"1585e4a1d13343309656d331280b38a3", "user_id": null}, "entity_id":
"sensor.toon_gas_used_cnt", "last_changed":
"2018-09-27T05:20:26.235972+00:00", "last_updated":
"2018-09-27T05:20:26.235972+00:00", "state": "40.215"}


"


Op do 27 sep. 2018 om 09:37 schreef Dennis Smit <dennis@dennissm.it>:

**Comment by Luc-S** [comment]
Ok, in principe verwacht ik ook een relatief leeg scherm als je niets geconfigureerd hebt dan alleen een connectie. Het kan ook zijn dat alles leeg is en er niet eens geprobeerd wordt om een connectie te maken.

Heb je wel de knop "Instellingen" rechts bovenin het scherm van je Toon? Als je daar op klikt zou je dit scherm moeten krijgen waar je je instellingen kwijt kan:
[https://github.com/Luc-S/Toon-HASS/blob/master/README%20images/configuration.png](https://github.com/Luc-S/Toon-HASS/blob/master/README%20images/configuration.png)

Om geen aannames te doen; Wat heb je in dat scherm allemaal staan? Je hoeft het niet letterlijk te typen hier op het openbare web, als je aangeeft wat er gevuld is dat is voldoende.

**Comment by dennis071nl** [comment]
Ik heb volgens mij geprobeerd met interne IP alswel duckdns adres.
Daarnaast ook knopje SSL aangezet en met verschillende poorten (zowel 443
als 8123) geprobeerd...

Helpt dat?



Op do 27 sep. 2018 om 09:58 schreef Luc_S <notifications@github.com>:

**Comment by Luc-S** [comment]
Omdat je certificaat op de duckdns naam staat zal je die moeten gebruiken. Op je router is als het goed is een port forwarding actief die 443 naar je HA op 8123 stuurt. Dan kun je ook beter 443 gebruiken (volgens mij doet 8123 het ook niet bij mij maar dat kan ik nu even niet testen).

Het scherm zal leeg blijven als je niets configureert. Probeer dit eens in te voeren;

Server IP: **jouw_duckdns_naam.duckdns.org**
Poort: **443**
Pass: **je_api_password**

SSL schakelaar aan.

In het blokje daaronder 'Sensoren':
1: **sensor.toon_gas_used_cnt**

Dan druk je rechtsboven op 'Opslaan'. Dan ben ik benieuwd of je in het hoofdscherm de sensor krijgt te zien, of dat er toch een melding komt.

**Comment by dennis071nl** [comment]
Luc,
ik krijg t hier niet lekker voor elkaar via VNC, dus moeten wachten tot
later.

Moet je bij sensoren de sensornaam handmatig invullen ? Ik was er namelijk
van uit gegaan dat dit gevuld werd met alle beschikbare sensoren die ie
allemaal vond in HA... maar wellicht is dat een beetje te geautomatiseerd
gedacht van me...:-))))

ik laat je weten hoe t gaat!

Dennis

Op do 27 sep. 2018 om 10:43 schreef Luc_S <notifications@github.com>:

**Comment by Luc-S** [comment]
Nee moet ik inderdaad nog doen. Iets met een isNxt variabele o.i.d. las ik, geen idee :p Ik zal daar eens induiken, moet jij maar laten weten of het werkt (heb zelf geen Toon 2). Ik maak daar wel even een nieuw issue van hier, kunnen we daar verder kletsen over Toon 2 compatibiliteit.

**Comment by dennis071nl** [comment]
check! let u know!

Wordt morgenavond schat ik in...! :-)



Op do 27 sep. 2018 om 11:36 schreef Luc_S <notifications@github.com>:

**Comment by kurniawan77** [comment]
Hier ook problemen met HA 0.80.3.

Heb net mijn gerooted Toon ontvangen en wilde HA op de Toon proberen. Helaas blijf ik "Could not establish connection" error zien. 
Als ik de api url uitvoer op een ander pc https://ha-url/api/states?api_password=wachtwoord_van_je_HA dan werkt het goed en krijg ik respons, ook met een sensor of switch

groet

**Comment by TheRedBull205** [comment]
Zijn er nog updates omtrend het nieuwe authenticatie systeem? Krijg het helaas niet meer voor elkaar via de API om deze app werkend te krijgen.

**Comment by Luc-S** [comment]
Het instellen van de SSL certificaten op de Toon is een vervelend klusje en het is mij soms niet helemaal duidelijk of het mis gaat bij SSL of met de app. Kun je aangeven met welke versie van Home Assistant het nog wel werkte?

Is het mogelijk voor jou om zonder SSL je Home Assistant te benaderen met de app?

**Comment by TheRedBull205** [comment]
Sorry voor mijn zeer late reactie, nu pas weer toegekomen om verder te gaan met mijn Toon / home assistant.

Toon versie: 5.2.11
Hassio versie: 0.92.1
Toon-HASS app version: 1.0.3 (toonstore)

Volgende toegevoegd aan configuration.yaml:
> homeassistant:
#https://www.home-assistant.io/docs/authentication/providers/
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.0.0/24
http:
#https://www.home-assistant.io/components/http/
  ssl_profile: intermediate

Nu krijg ik geen foutmelding meer in home assistant over ssl of authentication. Door de toon als trusted network te maken hoeft deze niet meer in te loggen dus heb het wachtwoord veld leeg gelaten. Helaas krijg ik geen goeie foutmelding op de toon:
![WhatsApp Image 2019-04-29 at 21 44 36](https://user-images.githubusercontent.com/17354992/56922292-1c298f80-6ac8-11e9-893f-5a92209e1025.jpeg)

Laatste keer werkend was na mijn weten rond 0.60 toen ik nog geen ssl/tls had. Gebruik nu de volgende duckdns/Let’s Encrypt addon:
https://www.home-assistant.io/addons/duckdns/

Ga komend weekend mn home assistant overzetten naar een virtuele instance, omdat te veel componenten falen. Denk dat mn rpi het niet meer aan kan wat ik allemaal wil. Maar zou dit niet mogen tegenwerken. Zal van het weekend ook nog verder opzoek gaan naar een mogelijke fix.

**Comment by Luc-S** [comment]
Hey @TheRedBull205, ik moet me nog steeds verdiepen in dat nieuwe authenticatie gebeuren. Zo te zien is het sinds 0.90 echt deprecated. Vreemd dat het bij mij nog steeds werkt, ik ben toevallig vorig weekend naar 0.92.1 gegaan.

Kun je de regel code in file HomeassistantApp.qml op regel 249:

`message = "Settings not saved. Could not establish connection. ResponseText: '" + http.responseText + "'";`

eens veranderen in:

`message = "URL: " + checkUrl;`

En dan even kijken met welke URL hij aan de slag gaat, klopt die? En ik weet niet meer waarom maar elke keer als hij geen goede connectie kan maken zet hij SSL terug naar NO. Dus die moet je ook elke keer weer even inschakelen.

**Comment by Luc-S** [comment]
Je kan tevens proberen of de URL te benaderen is via je Toon door hem via terminal op te vragen met curl:

`curl --insecure 'https://je_home_assistant_url'`

Ik kom er zojuist wel achter dat hij het bij mij alleen doet met de --insecure parameter. Zonder krijg ik: curl: (60) SSL certificate problem: unable to get local issuer certificate

Ik had al amper verstand van dat certificate gebeuren, kan dit er ook nog wel bij -.-" Het werkt namelijk verder wel gewoon hier...

**Comment by Luc-S** [comment]
Ik heb het zoals jij probeert @TheRedBull205 ook niet aan de praat kunnen krijgen. Als we een whitelist configureren met 192.168.x.x dan moeten we volgens mij ook verbinding maken met het lokale IP-adres van HomeAssistant en dus niet xxx.duckdns.org. Als we dat echter doen dan klopt het SSL certificaat weer niet want die is afgegeven op xxx.duckdns.org.

Een call naar xxx.duckdns.org registreert HomeAssistant als een benadering vanaf mijn extern IP-adres, dus die valt buiten de whitelist en krijg ik geen verbinding.

Ik ben op dit moment het nieuwe HomeAssistant authenticatie systeem aan het implementeren in de app inclusief wat betere foutmeldingen. Ik ga het proberen vanavond af te maken, dan is het een kwestie van een long-lived access token genereren en toevoegen aan Toon.

Info long-lived access token: 
[https://developers.home-assistant.io/docs/en/auth_api.html#long-lived-access-token](https://developers.home-assistant.io/docs/en/auth_api.html#long-lived-access-token)

Genereren access token kan vanuit je profiel in Home Assistant:
[https://www.home-assistant.io/docs/authentication/#your-account-profile](https://www.home-assistant.io/docs/authentication/#your-account-profile)

**Comment by Luc-S** [comment]
Ik moest toch nog wat meer aan de code sleutelen dan ik dacht :) Maar het zit erin. Ik heb het zelf wat getest maar hoor graag of het bij jullie ook werkt.

Er is een schuifje bijgekomen in het configuratie scherm om te kiezen voor 'Legacy pass'. Deze moet aan als je nog via de oude manier, dus met password, connectie wil maken.

Voor de long lived access token moet dat schuifje uit. Je krijgt in de Toon applicatie folder een token.txt file waarin je je token moet zetten, zonder quotes o.i.d.. Voor de token heb ik geen input vak gemaakt omdat dit een veel te lange string is om via de Toon in te voeren.

Home Assistant heeft een api waarmee je automatisch een token kan aanvragen maar dit heb ik niet kunnen maken omdat dit via web socket moet, de Qt versie op de Toon kan dit geloof ik niet.

Ik zal binnenkort kijken of ik een stukje how-to kan toevoegen aan de readme.

**Comment by TheRedBull205** [comment]
Heb de Toon store versie verwijderd en vervolgens de laatste versie van github geinstalleerd echter herkend de toon store de laatste versie als een toonstore versie...

Ben zelf niet bekend met het maken van apps voor de toon maar neem aan dat ik iets in de qmldir moet veranderen om dit tegen te gaan? Zodat de toon store hem niet herkend want mn toon kan de app vervolgens niet bouwen (.qmlc) of heb je een andere tip voor me zodat ik je nieuwe versie kan testen.

**Comment by Luc-S** [comment]
Dat zou niet uit mogen maken. Ik heb ook ooit de versie van de Toon store app gedownload en nu denkt hij inderdaad alsof het die nog altijd is. Je zou de files er gewoon overheen moeten kunnen zetten. De .qmlc files zijn cached files, die zou ik allemaal verwijderen in de homeassistant folder. Wie weet raakt hij in de knoop omdat die qmlc files niet overeen komen.

Laat maar even weten of het lukt. Anders kan ik hier ook eens kijken wat er gebeurd als ik nog eens de Toon store versie installeer en dan de nieuwe files er overheen zet.

Het kan overigens ook zijn dat na een toevoeging aan de userSettings.json deze niet meer zomaar geaccepteerd wordt. Misschien dat je alle .json files even in een aparte backup folder kan zetten en dan eens kan kijken of hij wel opstart.

**Comment by TheRedBull205** [comment]
Van alles geprobeerd maar krijg het helaas niet werkend, na een herstart maakt hij maar 1 .qmlc en 1 .json file aan. Dus ga er vanuit dat hier iets in mis gaat maar kan niks vinden in de logging op:
/mnt/data/qmf/log

![ToonHA](https://user-images.githubusercontent.com/17354992/57488529-a2598900-72b3-11e9-853d-3a7f1d054ada.PNG)

- versions aangepast zodat toonstore deze niet meer zag:
  /qmf/qml/apps/homeassistant-1.1.0/version.txt (bestand naar 1.1.0)
  /qmf/qml/apps/homeassistant-1.1.0/qmldir (bestand naar 1.1 insplaats van 1.0)
- Overschrijven van de /qmf/qml/apps/homeassistant-1.0.3/ met de bestanden van github
Uiteraard naar alles de gui gereset en omdat dit niet hielp de hele toon herstart.

Helaas in alle gevallen word er maar 1 .qmlc en 1 .json bestand aangemaakt en word de app niet zichtbaar aan de voorkant. Is er elders logging die ik kan inzien om te kijken waarom apps falen of is dit aan te zetten? Kan dit ook wel vragen op het domoticaforum.

Zal anders ook eens door je code heen om te zien hoe die alles opbouwt en waar het misschien op mis loopt.

**Comment by Luc-S** [comment]
Als je het in een nieuwe folder zet moet je hem misschien ook opnieuw aan een tile toewijzen of niet?

Maar dan lijkt het alsof er inderdaad toch nog een error is ingeslopen. Voor Qt logging moet je even de /etc/inittab wijzigen en dan kun je na een reboot de log zien met `cat /var/log/qt`. Zie [https://www.domoticaforum.eu/viewtopic.php?f=104&t=12369&p=90070&hilit=%2Fetc%2Finittab#p90068](https://www.domoticaforum.eu/viewtopic.php?f=104&t=12369&p=90070&hilit=%2Fetc%2Finittab#p90068)

Je ziet in de logging een blok waarin hij custom apps gaat opzetten, hopen dat er iets tussen staat (je kan de file ook even overzetten naar een pc en dan zoeken op homeassistant).

Vergeet de inittab ook niet weer terug te zetten want de Toon heeft niet veel ruimte.

**Comment by Luc-S** [comment]
Ok misschien heb ik wat gevonden. Ik was helemaal vergeten dat ik een tijdje geleden de schakelaar schuifjes niet meer mooi vond en nieuwe heb gemaakt. Deze nieuwe plaatsjes stonden nog niet op Github en heb ik nu in de drawables folder gezet.

Het gaat om de volgende plaatjes:

`knob.png`
`backgroundOff.png`
`backgroundOn.png`

**Comment by rwit-ormer** [comment]
ik kan nog geen connectie maken met de long-lived access token naar de HomeAssistant

Op de Toon:
_eneco-001-xxxxxx:~# curl 'https://[homeassistant address]:8123'
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option._


In HomeAssistant:
_Traceback (most recent call last):
  File "uvloop/sslproto.pyx", line 500, in uvloop.loop.SSLProtocol._on_handshake_complete
  File "uvloop/sslproto.pyx", line 484, in uvloop.loop.SSLProtocol._do_handshake
  File "/usr/local/lib/python3.7/ssl.py", line 763, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1056)_

**Comment by Luc-S** [comment]
Ik heb even geen pc bij de hand om bij mij de curl te checken. Kun je eens kijken wat de applicatie zegt als je in de HomeassistantApp.qml de debug optie op 1 zet (is een parameter ergens bovenaan)? Dan krijg je wat logging in de app op de toon als het goed is. Wel even `killall -9 qt-gui` doen.

**Comment by Luc-S** [comment]
@rwit-ormer Hier krijg ik dezelfde foutmelding als ik een https URL opvraag via het curl commando op de Toon. Zelfs een curl naar andere websites met SSL geven deze melding bij mij.

Als ik met de token een response wil krijgen via curl dan wordt het dit:

`curl --cacert "/etc/ssl/certs/DST_Root_CA_X3.pem" -H "Authorization: Bearer DLKjdf3eifj39849j_dummy_super_lange_token_dfjlejfrgh3898ldkf" https://dummy.duckdns.
org/api/`

Response: `{"message": "API running."}`

**Comment by TheRedBull205** [comment]
Vandaag m'n toon opnieuw opgestart en zie tot mijn verbazing ineens dat de toon verbinding heeft met mijn home assistant. Alle ingestelde states staan er ineens. Enige verschil dat ik zie met een maand geleden is een aantal updates:
Home assistant: V0.100.3
Toon softwareversie: V4.9.6
Toon TSC: V2.1.1
Toonstore: V3.0.3
Toonstore Home Assistant Controler: V1.0.4

- SSL staat aan
- Password via long-lived access token
- Poort: 8123
- Server ip : "test.duckdns.org" ([geen https er voor dit gebeurd door de code](https://github.com/Luc-S/Toon-HASS/blob/master/homeassistant/HomeassistantApp.qml#L259))

Dus alles lijkt weer te werken. Iemand anders die nog problemen heeft?

**Comment by Luc-S** [comment]
@TheRedBull205 Versie 1.0.4 van de Home Assistant Controller applicatie is relatief nieuw waarin er een aantal dingen zijn gewijzigd en gefixt. Wellicht daarin iets opgelost waar jij dan ook last van hebt gehad. 

Fijn dat het werkt nu :)
